# Generated by Django 5.2.1 on 2025-06-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_documentchunk_embedding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
    ]
