# Generated by Django 5.2.1 on 2025-06-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_delete_documentchunk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AlterModelOptions(
            name='chatuser',
            options={'verbose_name': 'Chat User', 'verbose_name_plural': 'Chat Users'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='research.chatuser'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='research.website'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
