# Generated by Django 5.2.1 on 2025-06-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_chatmessage_options_alter_chatuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
